version: 2
jobs:
  check:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: yarn install
      - run: yarn run build
      - run: yarn run prettier --list-different
      - run: yarn run eslint
      - run: yarn flow check
      - run: yarn run test --coverage
      - store_test_results:
          path: reports
      - store_artifacts:
          path: coverage/lcov-report
          destination: coverage

  deploy:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: yarn install
      - run: sudo yarn global add now --prefix /usr/local
      - run: echo "{\"alias\":\"$NOW_ALIAS\"}" > now.json
      - run: now --public --no-clipboard --token $NOW_TOKEN --env NODE_ENV=production --env APP_ID=$APP_ID --env LOG_LEVEL=$LOG_LEVEL --env WEBHOOK_SECRET=$WEBHOOK_SECRET --env PRIVATE_KEY=$PRIVATE_KEY --env SENTRY_DSN=$SENTRY_DSN
      - run: now --token $NOW_TOKEN alias
      - run: now --token $NOW_TOKEN rm autorebase --safe --yes

workflows:
  version: 2
  check-or-deploy:
    jobs:
      - check:
          filters:
            branches:
              ignore: master
      - deploy:
          filters:
            branches:
              only: master
