version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: yarn install
      - run: yarn run build
      - run: yarn run prettier --list-different
      - run: yarn run eslint
      - run: yarn flow check
      - run: yarn run test --coverage
      - store_test_results:
          path: reports
      - store_artifacts:
          path: coverage/lcov-report
          destination: coverage
